# Generated by Django 3.2.4 on 2021-07-10 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('airblue', '0004_auto_20210708_1429'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productremains',
            unique_together={('product', 'productvariant')},
        ),
    ]
