# Generated by Django 3.2.4 on 2021-08-10 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airblue', '0006_auto_20210810_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(to='airblue.Category', verbose_name='categories'),
        ),
    ]
