# Generated by Django 3.2.4 on 2021-08-10 18:56

from django.db import migrations


def transferFKtoM2M(apps, schema_editor):

    Product = apps.get_model('airblue', 'Product')

    ProductToCategory = Product.categories.through

    ProductToCategory.objects.bulk_create([
        ProductToCategory(
            product=product,
            category=product.category
        ) for product in Product.objects.all()
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('airblue', '0007_product_categories'),
    ]

    operations = [
        migrations.RunPython(
            transferFKtoM2M, reverse_code=migrations.RunPython.noop
        ),
    ]
