# Generated by Django 3.2.4 on 2021-08-13 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airblue', '0009_auto_20210810_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='style',
            field=models.JSONField(default=dict, verbose_name='Style'),
        ),
    ]
