# Generated by Django 3.2.4 on 2021-08-24 20:14

from django.db import migrations
from django.utils.translation import gettext, activate
from django.conf import settings


def create_remains(apps, schema_editor):

    Product = apps.get_model('airblue', 'Product')
    ProductRemains = apps.get_model('airblue', 'ProductRemains')
    ProductVariant = apps.get_model('airblue', 'ProductVariant')

    activate(settings.LANGUAGE_CODE)
    try:
        empty_variant = ProductVariant.objects.get(
            name=gettext('Variants missing')
        )
    except ProductVariant.DoesNotExist:
        empty_variant = ProductVariant(name=gettext('Variants missing'))
        empty_variant.save()

    ProductRemains.objects.bulk_create([
        ProductRemains(
            product=product,
            productvariant=empty_variant,
            # This price is not supposed to be seen in production as from now
            # on we are supposed to always create ProductRemains alongside
            # legit Product objects
            price=123,
        ) for product in Product.objects.exclude(
            id__in=ProductRemains.objects.values_list(
                'product', flat=True
            ).distinct()
        )
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('airblue', '0011_alter_productremains_remains'),
    ]

    operations = [
        migrations.RunPython(
            create_remains, reverse_code=migrations.RunPython.noop
        ),
    ]
