# Generated by Django 3.2.4 on 2021-08-28 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('airblue', '0013_auto_20210828_1950'),
    ]

    operations = [
        migrations.CreateModel(
            name='Miles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='miles', to=settings.AUTH_USER_MODEL, verbose_name='Miles')),
            ],
            options={
                'verbose_name': 'Miles',
                'verbose_name_plural': 'Miles',
            },
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
