# Generated by Django 3.2.4 on 2021-08-28 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('airblue', '0014_auto_20210828_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='miles',
            name='miles',
            field=models.PositiveIntegerField(default=1, verbose_name='Miles'),
        ),
        migrations.AlterField(
            model_name='miles',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
