# Generated by Django 3.2.4 on 2021-08-29 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airblue', '0015_auto_20210828_2010'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('originPrice', models.PositiveIntegerField()),
                ('discountPrice', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('star', models.PositiveIntegerField()),
                ('isNew', models.BooleanField()),
                ('isHot', models.BooleanField()),
                ('isFreeShipping', models.BooleanField()),
            ],
        ),
    ]
