# Generated by Django 3.2.4 on 2021-10-08 18:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('airblue', '0018_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='blacklist_user',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
