# Generated by Django 3.2.4 on 2021-10-10 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airblue', '0020_userorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(default=1, verbose_name='coupon_value')),
                ('code', models.CharField(max_length=128, unique=True, verbose_name='code')),
                ('used', models.BooleanField(default=False)),
            ],
        ),
    ]
