# Generated by Django 3.2.4 on 2021-11-06 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airblue', '0023_redeemeduser'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserItemChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('item', models.ManyToManyField(blank=True, to='airblue.Items')),
            ],
        ),
    ]
